In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('winequality-red.csv',sep=';')

### Data Preprocessing

In [2]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
df.shape

(1599, 12)

In [5]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

## Explanation For Fit_Transform

In [24]:
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
from sklearn.linear_model import LinearRegression
help(LinearRegression.fit)

Help on function fit in module sklearn.linear_model.base:

fit(self, X, y, sample_weight=None)
    Fit linear model.
    
    Parameters
    ----------
    X : array-like or sparse matrix, shape (n_samples, n_features)
        Training data
    
    y : array_like, shape (n_samples, n_targets)
        Target values. Will be cast to X's dtype if necessary
    
    sample_weight : numpy array of shape [n_samples]
        Individual weights for each sample
    
        .. versionadded:: 0.17
           parameter *sample_weight* support to LinearRegression.
    
    Returns
    -------
    self : returns an instance of self.



In [26]:
me=ss.fit(x2)
me.mean_

array([4., 5., 6.])

In [27]:
np.std(x2[:,2])

2.449489742783178

In [28]:
x3=np.array([[10,11,12],[13,14,15],[16,17,18]])
x3

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
np.std(x3[:,2])

2.449489742783178

In [30]:
me.transform(x3)

array([[2.44948974, 2.44948974, 2.44948974],
       [3.67423461, 3.67423461, 3.67423461],
       [4.89897949, 4.89897949, 4.89897949]])

# Data Scaling

Data Scaling is performed to convert all data in same scale because variable with larger value will have more impact on our model which will decrease the performance of model.

### 1 Standard Scalar
- z=x-u/s

In [31]:
x=np.array([[-400],[-100],[0],[100],[400]])
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [32]:
from sklearn import preprocessing

In [33]:
ss=preprocessing.StandardScaler()

In [34]:
ss.fit_transform(x)


array([[-1.53392998],
       [-0.38348249],
       [ 0.        ],
       [ 0.38348249],
       [ 1.53392998]])

In [35]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

## Cross-Varification

In [36]:
np.std(x)

260.76809620810593

In [37]:
(100-0)/np.std(x)

0.38348249442368526

In [38]:
df1=df.values
df1

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [39]:
df1

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [40]:
ss.fit_transform(df1)

array([[-0.52835961,  0.96187667, -1.39147228, ..., -0.57920652,
        -0.96024611, -0.78782264],
       [-0.29854743,  1.96744245, -1.39147228, ...,  0.1289504 ,
        -0.58477711, -0.78782264],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.04808883,
        -0.58477711, -0.78782264],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.54204194,
         0.54162988,  0.45084835],
       [-1.39015528,  0.65462046, -0.77526673, ...,  0.30598963,
        -0.20930812, -0.78782264],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.01092425,
         0.54162988,  0.45084835]])

## 2 Min-Max Scaler
- x-min(x)/x(max)-x(min)

In [41]:
mm=preprocessing.MinMaxScaler(feature_range=(0,1))

In [42]:
x=np.array([[-400],[-100],[0],[100],[400]])
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [43]:
mm.fit_transform(x)

array([[0.   ],
       [0.375],
       [0.5  ],
       [0.625],
       [1.   ]])

## Cross-Varification

In [44]:
(400-np.min(x))/(np.max(x)-np.min(x))

1.0

In [45]:
(100-np.min(x))/(np.max(x)-np.min(x))

0.625

In [46]:
mm.fit_transform(x2)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [47]:
(5-np.min(x2))/(np.max(x2)-np.min(x2))

0.5

In [48]:
mm.fit_transform(df1)

array([[0.24778761, 0.39726027, 0.        , ..., 0.13772455, 0.15384615,
        0.4       ],
       [0.28318584, 0.52054795, 0.        , ..., 0.20958084, 0.21538462,
        0.4       ],
       [0.28318584, 0.43835616, 0.04      , ..., 0.19161677, 0.21538462,
        0.4       ],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.25149701, 0.4       ,
        0.6       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.22754491, 0.27692308,
        0.4       ],
       [0.12389381, 0.13013699, 0.47      , ..., 0.19760479, 0.4       ,
        0.6       ]])

## 3 MaxAbsScaler
- x/max(abs(x))

In [49]:
ma=preprocessing.MaxAbsScaler()

In [50]:
ma.fit_transform(x)

array([[-1.  ],
       [-0.25],
       [ 0.  ],
       [ 0.25],
       [ 1.  ]])

In [51]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ma.fit_transform(x2)

array([[0.14285714, 0.25      , 0.33333333],
       [0.57142857, 0.625     , 0.66666667],
       [1.        , 1.        , 1.        ]])

## Cross-Validation

In [53]:
100/np.max(abs(x))

0.25

In [54]:
-400/np.max(abs(x))

-1.0

In [55]:
5/np.max(abs(x2[:,1]))

0.625

## 4 Noramalizer
## Max Normalizer
- x/max(x)

In [56]:
norm=preprocessing.Normalizer(norm='max')

In [57]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [58]:
norm.fit_transform(x)

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [59]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
norm.fit_transform(x2)

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

## Cross-Validation

In [61]:
-400/np.max(x[0])

1.0

In [62]:
x2[0]

array([1, 2, 3])

In [63]:
1/np.max(x2[0,:])

0.3333333333333333

## l1 Normalizer
- x_normalizer=x/sum(x)

In [64]:
l1_norm=preprocessing.Normalizer(norm='l1')

In [65]:
l1_norm.fit_transform(x)

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

In [66]:
l1_norm.fit_transform(x2)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.29166667, 0.33333333, 0.375     ]])

## Cross-Validation

In [67]:
-400/np.sum(x[0,:])

1.0

In [68]:
5/np.sum(x2[1,:])

0.3333333333333333

## l2-Normalize
- x/sqrt(sum(i**2)for i in x)

In [69]:
l2_norm=preprocessing.Normalizer(norm='l2')

In [70]:
l2_norm.fit_transform(x)

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

In [71]:
l2_norm.fit_transform(x2)

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.50257071, 0.57436653, 0.64616234]])

## Cross-Validation

In [72]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a=[sum(i**2) for i in x2]
a

[14, 77, 194]

In [74]:
-100/np.sqrt([sum(i**2) for i in x])[1]

-1.0

In [75]:
a=[sum(i**2) for i in x2]
5/np.sqrt(a)[1]

0.5698028822981898

## 5 Binarizer

In [76]:
bin=preprocessing.Binarizer(threshold=0.5)

In [77]:
bin.fit_transform(x)

array([[0],
       [0],
       [0],
       [1],
       [1]])

In [78]:
bin.fit_transform(x2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])