In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('credit_demo.csv',na_values=['n/a','N/A','NA','NAN','','Missing'])

In [3]:
df.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE   AGE  PAY_HISTORY  \
0   1      20000    MALE          3         2  35.0           -1   
1   2     260000  FEMALE          1         2  51.0           -1   
2   3     360000  FEMALE          1         1  49.0           -2   
3   4     450000  FEMALE          1         1  40.0           -2   
4   5      50000  FEMALE          3         1  47.0           -1   

       BILL_AMT       PAY_AMT  default  
0   4486.500000   2354.833333        0  
1  14728.166670  11051.333330        0  
2      0.000000      0.000000        0  
3   4494.166667   3764.833333        1  
4   6701.333333   6594.500000        0

In [4]:
df.columns

Index(['ID', 'LIMIT_BAL', 'GENDER', 'EDUCATION', 'MARRIAGE', 'AGE',
       'PAY_HISTORY', 'BILL_AMT', 'PAY_AMT', 'default'],
      dtype='object')

In [41]:
df.shape

(2991, 10)

In [6]:
df_train=df.sample(frac=0.8)

In [7]:
df_test=df.drop(df_train.index)

In [8]:
df_test.shape

(598, 10)

In [9]:
df.default.value_counts()

0    2000
1     991
Name: default, dtype: int64

In [10]:
df_train.default.value_counts()

0    1606
1     787
Name: default, dtype: int64

In [11]:
(df_train.default.value_counts()/df_train.shape[0])*100

0    67.112411
1    32.887589
Name: default, dtype: float64

In [13]:
(df_test.default.value_counts()/df_test.shape[0])*100

0    65.886288
1    34.113712
Name: default, dtype: float64

In [17]:
df_train.isnull().sum()

ID              0
LIMIT_BAL       0
GENDER          0
EDUCATION       0
MARRIAGE        0
AGE            19
PAY_HISTORY     0
BILL_AMT        0
PAY_AMT         0
default         0
dtype: int64

In [21]:
pd.options.display.float_format='{:.2f}'.format
df_train.describe()

ID  LIMIT_BAL  EDUCATION  MARRIAGE     AGE  PAY_HISTORY  BILL_AMT  \
count 2393.00    2393.00    2393.00   2393.00 2374.00      2393.00   2393.00   
mean  1483.26  189674.05       1.72      1.48   36.81        -0.08  19789.90   
std    867.39  130172.17       0.75      0.52    9.35         1.70  40438.57   
min      1.00   10000.00       0.00      0.00   21.00        -2.00  -4465.83   
25%    731.00   80000.00       1.00      1.00   29.00        -1.00   1391.00   
50%   1481.00  180000.00       2.00      1.00   36.00        -1.00   4549.50   
75%   2230.00  270000.00       2.00      2.00   43.00         2.00  18364.17   
max   3000.00  800000.00       6.00      3.00   91.00         8.00 456957.50   

        PAY_AMT  default  
count   2393.00  2393.00  
mean    5195.41     0.33  
std     9321.25     0.47  
min        0.00     0.00  
25%      862.50     0.00  
50%     2108.83     0.00  
75%     5442.33     1.00  
max   119071.50     1.00

## Uni-Variate Analysis

In [28]:
df_train.LIMIT_BAL.quantile(np.arange(0,1,.1))

0.00    10000.00
0.10    30000.00
0.20    60000.00
0.30   100000.00
0.40   140000.00
0.50   180000.00
0.60   200000.00
0.70   240000.00
0.80   300000.00
0.90   360000.00
Name: LIMIT_BAL, dtype: float64

In [29]:
(df_train.LIMIT_BAL>500000).sum()

15

In [31]:
df_train.EDUCATION.unique()

array([1, 3, 2, 5, 4, 6, 0], dtype=int64)

In [63]:
df_train.iloc[1]

ID                613
LIMIT_BAL      450000
GENDER         FEMALE
EDUCATION           1
MARRIAGE            2
AGE             28.00
PAY_HISTORY        -1
BILL_AMT      3520.83
PAY_AMT       3577.50
default             0
Name: 611, dtype: object

In [64]:
df_train.loc[1]

ID                   2
LIMIT_BAL       260000
GENDER          FEMALE
EDUCATION            1
MARRIAGE             2
AGE              51.00
PAY_HISTORY         -1
BILL_AMT      14728.17
PAY_AMT       11051.33
default              0
Name: 1, dtype: object

In [20]:
df_train.GENDER.unique()

array(['MALE', 'FEMALE'], dtype=object)

In [21]:
df[df.GENDER=='MALE']['default'].value_counts()/df.shape[0]*100

0   23.44
1   14.71
Name: default, dtype: float64

In [22]:
pd.crosstab(df_train.default,df_train.GENDER,margins=True)

GENDER   FEMALE  MALE   All
default                    
0          1043   565  1608
1           427   358   785
All        1470   923  2393

In [23]:
df.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE   AGE  PAY_HISTORY  BILL_AMT  \
0   1      20000    MALE          3         2 35.00           -1   4486.50   
1   2     260000  FEMALE          1         2 51.00           -1  14728.17   
2   3     360000  FEMALE          1         1 49.00           -2      0.00   
3   4     450000  FEMALE          1         1 40.00           -2   4494.17   
4   5      50000  FEMALE          3         1 47.00           -1   6701.33   

   PAY_AMT  default  
0  2354.83        0  
1 11051.33        0  
2     0.00        0  
3  3764.83        1  
4  6594.50        0

In [24]:
df_train.MARRIAGE.unique()

array([1, 2, 3, 0], dtype=int64)

In [68]:
pd.crosstab(df_train.default,df_train.MARRIAGE,margins=True)/df_train.shape[0]*100

MARRIAGE    0     1     2    3    All
default                              
0        0.08 35.69 31.05 0.29  67.11
1        0.04 16.46 15.92 0.46  32.89
All      0.13 52.15 46.97 0.75 100.00

In [69]:
df_train.PAY_HISTORY.unique()

array([-1,  2,  7, -2,  3,  5,  6,  8,  4], dtype=int64)

In [70]:
pd.crosstab(df_train.default,df_train.PAY_HISTORY,margins=True)/df_train.shape[0]*100

PAY_HISTORY   -2    -1     2    3    4    5    6    7    8    All
default                                                          
0           0.04 66.86  0.00 0.00 0.00 0.04 0.00 0.17 0.00  67.11
1           4.81  0.00 23.53 2.59 0.46 0.17 0.17 1.09 0.08  32.89
All         4.85 66.86 23.53 2.59 0.46 0.21 0.17 1.25 0.08 100.00

In [71]:
def get(x):
    if x < 100000:
        return 'Low'
    if 100000<=x<200000:
        return 'Medium'
    if x>=200000:
        return 'High'
        

In [72]:
df_train['Limit']=df_train.LIMIT_BAL.apply(get)

In [73]:
df_train.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE   AGE  PAY_HISTORY  \
1250  1254     140000  FEMALE          1         2 25.00           -1   
611    613     450000  FEMALE          1         2 28.00           -1   
1610  1614     300000    MALE          1         1 30.00           -1   
1939  1943     310000  FEMALE          3         2 36.00           -1   
1868  1872     400000  FEMALE          2         1 46.00           -1   

      BILL_AMT  PAY_AMT  default   Limit  
1250   1567.33  1563.50        0  Medium  
611    3520.83  3577.50        0    High  
1610   2059.17  2203.17        0    High  
1939   3659.33  3377.17        0    High  
1868  71288.17 72530.00        0    High

In [74]:
(pd.crosstab(df_train.default,df_train.Limit,margins=True)/df_train.shape[0]*100)

Limit    High   Low  Medium    All
default                           
0       38.11 10.78   18.22  67.11
1        7.10 17.80    7.98  32.89
All     45.22 28.58   26.20 100.00

In [75]:
df_train.isnull().sum()

ID              0
LIMIT_BAL       0
GENDER          0
EDUCATION       0
MARRIAGE        0
AGE            19
PAY_HISTORY     0
BILL_AMT        0
PAY_AMT         0
default         0
Limit           0
dtype: int64

In [76]:
df_train['AGE']=df_train.AGE.fillna(df_train.AGE.mean())

In [77]:
df_train.AGE.quantile(np.arange(0,1,.01))

0.00   21.00
0.01   23.00
0.02   23.00
0.03   23.00
0.04   24.00
        ... 
0.95   54.00
0.96   55.00
0.97   57.00
0.98   58.00
0.99   60.08
Name: AGE, Length: 100, dtype: float64

In [78]:
(df_train.AGE>70).sum()

2

In [79]:
avg=df_train.AGE.mean()
avg

36.8066554338669

In [80]:
df_train.loc[(df_train.AGE>70),'AGE']=avg

In [81]:
df_train.AGE.max()

69.0

In [82]:
def get_age(x):
    if 21<=x<29:
        return 'lessthan30'
    elif 29<=x<35:
        return 'between29-35'
    elif 35<=x<45:
        return 'between35-45'
    else:
        return 'morethan45'


In [40]:
df_train['age_bkt']=df_train.AGE.map(get_age)

In [41]:
df_train.age_bkt.head()

2043      morethan45
1160    between35-45
1784    between35-45
1674    between29-35
1940    between35-45
Name: age_bkt, dtype: object

In [42]:
pd.options.display.float_format='{:.4f}'.format
pd.crosstab(df_train.default,df_train.age_bkt,margins=True)/df_train.shape[0]*100

age_bkt  between29-35  between35-45  lessthan30  morethan45      All
default                                                             
0             17.9273       24.1538     11.9933     13.1216  67.1960
1              7.0623        9.9039      9.1935      6.6444  32.8040
All           24.9896       34.0577     21.1868     19.7660 100.0000

In [43]:
df_train.BILL_AMT.describe()

count     2393.0000
mean     19729.8402
std      40540.6787
min      -4465.8333
25%       1386.8333
50%       4623.8333
75%      18661.8333
max     456957.5000
Name: BILL_AMT, dtype: float64

In [44]:
def get_bill(x):
    if x<5000:
        return 'Low'
    elif x<20000:
        return 'Medium'
    else:
        return 'High'

In [45]:
df_train['bill_bkt']=df_train.BILL_AMT.map(get_bill)

In [46]:
df_train.bill_bkt.head()

2043    High
1160     Low
1784     Low
1674     Low
1940     Low
Name: bill_bkt, dtype: object

In [47]:
pd.crosstab(df_train.default,df_train.bill_bkt,margins=True)/df_train.shape[0]*100

bill_bkt    High     Low  Medium      All
default                                  
0         5.0146 43.7526 18.4288  67.1960
1        18.4288  7.4802  6.8951  32.8040
All      23.4434 51.2328 25.3239 100.0000

In [48]:
df_train.PAY_AMT.describe()

count     2393.0000
mean      5391.3114
std      12378.0573
min          0.0000
25%        833.3333
50%       2069.1667
75%       5455.0000
max     385692.0000
Name: PAY_AMT, dtype: float64

In [49]:
def get_pay(x):
    if x<833:
        return 'Low'
    elif x<5281:
        return 'Medium'
    else:
        return 'High'

In [50]:
df_train['pay_bkt']=df_train.PAY_AMT.map(get_pay)

In [51]:
df_train.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE     AGE  PAY_HISTORY  \
2043  2047      80000    MALE          2         1 60.0000            2   
1160  1164     120000  FEMALE          2         2 37.0000           -1   
1784  1788     160000  FEMALE          2         2 40.0000           -1   
1674  1678     170000  FEMALE          2         1 34.0000           -1   
1940  1944     320000    MALE          1         1 40.0000           -1   

       BILL_AMT   PAY_AMT  default   Limit       age_bkt bill_bkt pay_bkt  
2043 50818.8333 1816.6667        1     Low    morethan45     High  Medium  
1160  3613.5000 3674.5000        0  Medium  between35-45      Low  Medium  
1784   632.1667  688.6667        0  Medium  between35-45      Low     Low  
1674  1223.8333  960.3333        0  Medium  between29-35      Low  Medium  
1940   430.0000  430.0000        0    High  between35-45      Low     Low

In [52]:
pd.crosstab(df_train.default,df_train.EDUCATION,margins=True)/df_train.shape[0]*100

EDUCATION      0       1       2       3      4      5      6      All
default                                                               
0         0.1672 34.2666 23.6941  8.4413 0.1672 0.2925 0.1672  67.1960
1         0.0000  9.2353 17.5094  6.0176 0.0418 0.0000 0.0000  32.8040
All       0.1672 43.5019 41.2035 14.4588 0.2089 0.2925 0.1672 100.0000

In [53]:
df_train.drop(df_train.query("EDUCATION==0 | EDUCATION>3").index,inplace=True)

In [54]:
def get_edu(x):
    if x==1:
        return 'Graduate'
    if x==2:
        return 'University'
    if x==3:
        return 'HighSchool'

In [55]:
df_train['Edu']=df_train.EDUCATION.map(get_edu)

In [56]:
df_train.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE     AGE  PAY_HISTORY  \
2043  2047      80000    MALE          2         1 60.0000            2   
1160  1164     120000  FEMALE          2         2 37.0000           -1   
1784  1788     160000  FEMALE          2         2 40.0000           -1   
1674  1678     170000  FEMALE          2         1 34.0000           -1   
1940  1944     320000    MALE          1         1 40.0000           -1   

       BILL_AMT   PAY_AMT  default   Limit       age_bkt bill_bkt pay_bkt  \
2043 50818.8333 1816.6667        1     Low    morethan45     High  Medium   
1160  3613.5000 3674.5000        0  Medium  between35-45      Low  Medium   
1784   632.1667  688.6667        0  Medium  between35-45      Low     Low   
1674  1223.8333  960.3333        0  Medium  between29-35      Low  Medium   
1940   430.0000  430.0000        0    High  between35-45      Low     Low   

             Edu  
2043  University  
1160  University  
1784  University  
1674  University  
1940    Graduate

In [57]:
pd.crosstab(df_train.default,df_train.Edu,margins=True)/df_train.shape[0]*100

Edu      Graduate  HighSchool  University      All
default                                           
0         34.5554      8.5124     23.8938  66.9617
1          9.3131      6.0683     17.6570  33.0383
All       43.8685     14.5807     41.5508 100.0000

In [58]:
pd.crosstab(df_train.default,df_train.MARRIAGE,margins=True)/df_train.shape[0]*100

MARRIAGE      0       1       2      3      All
default                                        
0        0.0843 35.5668 30.9735 0.3371  66.9617
1        0.0421 16.0556 16.4770 0.4635  33.0383
All      0.1264 51.6224 47.4505 0.8007 100.0000

In [59]:
df_train.drop(df_train.query("MARRIAGE==0 | MARRIAGE>2").index,inplace=True)

In [60]:
df_train.MARRIAGE.head()

2043    1
1160    2
1784    2
1674    1
1940    1
Name: MARRIAGE, dtype: int64

In [61]:
pd.crosstab(df_train.default,df_train.MARRIAGE,margins=True)/df_train.shape[0]*100

MARRIAGE       1       2      All
default                          
0        35.8996 31.2633  67.1629
1        16.2059 16.6312  32.8371
All      52.1055 47.8945 100.0000

In [62]:
df_train.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE     AGE  PAY_HISTORY  \
2043  2047      80000    MALE          2         1 60.0000            2   
1160  1164     120000  FEMALE          2         2 37.0000           -1   
1784  1788     160000  FEMALE          2         2 40.0000           -1   
1674  1678     170000  FEMALE          2         1 34.0000           -1   
1940  1944     320000    MALE          1         1 40.0000           -1   

       BILL_AMT   PAY_AMT  default   Limit       age_bkt bill_bkt pay_bkt  \
2043 50818.8333 1816.6667        1     Low    morethan45     High  Medium   
1160  3613.5000 3674.5000        0  Medium  between35-45      Low  Medium   
1784   632.1667  688.6667        0  Medium  between35-45      Low     Low   
1674  1223.8333  960.3333        0  Medium  between29-35      Low  Medium   
1940   430.0000  430.0000        0    High  between35-45      Low     Low   

             Edu  
2043  University  
1160  University  
1784  University  
1674  University  
1940    Graduate

In [63]:
df_train.PAY_HISTORY.unique()

array([ 2, -1,  3, -2,  4,  7,  6,  5,  8], dtype=int64)

In [64]:
pd.crosstab(df_train.default,df_train.PAY_HISTORY,margins=True)/df_train.shape[0]*100

PAY_HISTORY     -2      -1       2      3      4      5      6      7      8  \
default                                                                        
0           0.0425 66.9077  0.0000 0.0000 0.0000 0.0000 0.0000 0.2127 0.0000   
1           4.5087  0.0000 23.5644 2.5521 0.6380 0.2127 0.2552 1.0208 0.0851   
All         4.5513 66.9077 23.5644 2.5521 0.6380 0.2127 0.2552 1.2335 0.0851   

PAY_HISTORY      All  
default               
0            67.1629  
1            32.8371  
All         100.0000

In [65]:
def get_his(x):
    if x==-2:
        return 'left'
    if x==-1:
        return 'dulypaid'
    else:
        return 'Noise'

In [66]:
df_train['payhis_bkt']=df_train.PAY_HISTORY.map(get_his)

In [67]:
df_train.head()

ID  LIMIT_BAL  GENDER  EDUCATION  MARRIAGE     AGE  PAY_HISTORY  \
2043  2047      80000    MALE          2         1 60.0000            2   
1160  1164     120000  FEMALE          2         2 37.0000           -1   
1784  1788     160000  FEMALE          2         2 40.0000           -1   
1674  1678     170000  FEMALE          2         1 34.0000           -1   
1940  1944     320000    MALE          1         1 40.0000           -1   

       BILL_AMT   PAY_AMT  default   Limit       age_bkt bill_bkt pay_bkt  \
2043 50818.8333 1816.6667        1     Low    morethan45     High  Medium   
1160  3613.5000 3674.5000        0  Medium  between35-45      Low  Medium   
1784   632.1667  688.6667        0  Medium  between35-45      Low     Low   
1674  1223.8333  960.3333        0  Medium  between29-35      Low  Medium   
1940   430.0000  430.0000        0    High  between35-45      Low     Low   

             Edu payhis_bkt  
2043  University      Noise  
1160  University   dulypaid  
1784  University   dulypaid  
1674  University   dulypaid  
1940    Graduate   dulypaid

In [72]:
df_train['Marriage']=df_train.MARRIAGE.map(lambda x: 1 if x==1 else 0)

In [73]:
df_train.columns

Index(['GENDER', 'MARRIAGE', 'default', 'Limit', 'age_bkt', 'bill_bkt',
       'pay_bkt', 'Edu', 'payhis_bkt', 'Marriage'],
      dtype='object')

In [77]:
df_train.drop('MARRIAGE',axis=1,inplace=True)

In [78]:
df_train.head()

GENDER  default   Limit       age_bkt bill_bkt pay_bkt         Edu  \
2043    MALE        1     Low    morethan45     High  Medium  University   
1160  FEMALE        0  Medium  between35-45      Low  Medium  University   
1784  FEMALE        0  Medium  between35-45      Low     Low  University   
1674  FEMALE        0  Medium  between29-35      Low  Medium  University   
1940    MALE        0    High  between35-45      Low     Low    Graduate   

     payhis_bkt  Marriage  
2043      Noise         1  
1160   dulypaid         0  
1784   dulypaid         0  
1674   dulypaid         1  
1940   dulypaid         1

In [79]:
df_train=pd.get_dummies(df_train,drop_first=True)

In [80]:
df_train.head()

default  Marriage  GENDER_MALE  Limit_Low  Limit_Medium  \
2043        1         1            1          1             0   
1160        0         0            0          0             1   
1784        0         0            0          0             1   
1674        0         1            0          0             1   
1940        0         1            1          0             0   

      age_bkt_between35-45  age_bkt_lessthan30  age_bkt_morethan45  \
2043                     0                   0                   1   
1160                     1                   0                   0   
1784                     1                   0                   0   
1674                     0                   0                   0   
1940                     1                   0                   0   

      bill_bkt_Low  bill_bkt_Medium  pay_bkt_Low  pay_bkt_Medium  \
2043             0                0            0               1   
1160             1                0            0               1   
1784             1                0            1               0   
1674             1                0            0               1   
1940             1                0            1               0   

      Edu_HighSchool  Edu_University  payhis_bkt_dulypaid  payhis_bkt_left  
2043               0               1                    0                0  
1160               0               1                    1                0  
1784               0               1                    1                0  
1674               0               1                    1                0  
1940               0               0                    1                0

In [52]:
ch=pd.DataFrame([12,32,43,123],index=['A','B','C','D'],columns=['Hmm'])
ch

Hmm
A   12
B   32
C   43
D  123

In [61]:
ch.iloc[2]

Hmm    43
Name: C, dtype: int64