In [8]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('advertising.csv')

In [4]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
x=df.drop('Sales',axis=1)
x=x.drop('Unnamed: 0',axis=1)
y=df.Sales

In [6]:
x.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

## Ridge Regression

In [53]:
regR=linear_model.Ridge(alpha=0,fit_intercept=True,normalize=True)
regR=regR.fit(x,y)

In [54]:
print(regR.intercept_,regR.coef_)

2.938889369459412 [ 0.04576465  0.18853002 -0.00103749]


In [126]:
regR=linear_model.Ridge(alpha=10**-8,fit_intercept=True,normalize=True)
regR=regR.fit(x,y)

In [127]:
print(regR.intercept_,regR.coef_)

2.9388894645156807 [ 0.04576465  0.18853001 -0.00103749]


In [128]:
regR.predict([[5,10,20]])

array([5.03226299])

In [129]:
x.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [130]:
regR.predict([[230.1,37.8,69.2]])

array([20.52397437])

In [76]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [31]:
help(regR.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.ridge.Ridge instance
    Predict using the linear model
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape (n_samples,)
        Returns predicted values.



## Lasso Regressiona

In [32]:
regL=linear_model.Lasso(alpha=0,fit_intercept=True)
regL=regL.fit(x,y)

In [33]:
print(regL.coef_,regL.intercept_)

[ 0.04576465  0.18853002 -0.00103749] 2.938889369459412


In [36]:
regL=linear_model.Lasso(alpha=0.1,fit_intercept=True,normalize=True)
regL=regL.fit(x,y)

In [37]:
print(regL.coef_,regL.intercept_)

[0.03009928 0.09746336 0.        ] 7.329238330332901


In [38]:
regL.predict([[17,45,68]])

array([12.22677757])

## ElasticNet

In [51]:
regE=linear_model.ElasticNet(alpha=0.5,l1_ratio=1,fit_intercept=True,normalize=True)
regE.fit(x,y)

ElasticNet(alpha=0.5, copy_X=True, fit_intercept=True, l1_ratio=1,
           max_iter=1000, normalize=True, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [52]:
print(regE.coef_,regE.intercept_)

[0. 0. 0.] 14.0225
